### PR TITLE
add support for Ki / Grit / Sorcerer points

### PR DESCRIPTION
**Pull request by baldurmen**
I'm not sure I like the "Ki / Grit / Sorcerer Points" label but I couldn't find something generic that encompassed everything...

Happy to change things if you want me to!

### CODE REVIEW

**Comment by derikb** [comment]
Could just call them "Class points"? Not actually played any class that uses those, so I'm not sure. Will consult my PHB later.

**Comment by derikb** [comment]
@baldurmen I spent the weekend doing a lot of refactoring to use native Web Components in the UI. I'll add this param as part of that since this PR won't be mergable into the new code (which isn't quite ready yet but close).

**Comment by baldurmen** [comment]
No problem!

**Comment by derikb** [comment]
@baldurmen This is now in the latest release (from yesterday).

**Pull request closed without merging**
