### PR TITLE
WIP: Add a "Companion" tab

### PR DESCRIPTION
**Pull request by baldurmen**
Obviously still a WIP, but I think it would be very nice to be able to track a Companion Animal in a separate tab instead of having to create a whole new character.

### CODE REVIEW

**Comment by baldurmen** [comment]
This seems to work properly :)

If you want, I could add a button on the main Char tab that would show/hide the Companion tab ('Beast Master: [ ]'), but I didn't feel it was necessary and most people might miss it.

**Comment by derikb** [comment]
With all the similar property names (and how many they are), this might work better as a separate class for the companion. That would complicate some of the other code, but it also seems like it would be the cleaner way to go, the character class already has a ridiculous number of properties in it.

With a separate class for the companion then it could just be a single prop on the character storing the class that is the companion. Since we'd only need the `cpn_` prefix for the UI, then the companion coud use the same props as the main character class, so we could probably just make a base class and then extend each for the main and companion characters. (I guess theoretically it could just be the same class, but then we end up with a ton of unused fields for the companion that would just make the save data bigger).

Then the UI code would just need to account for the companion prop and the cpn_ prefix when saving/restoring.

And now I'm thinking such a setup could then also be used for the new... I forget the name, but the rule in the newish boxset that gives you a NPC/humanoid companion.

**Comment by baldurmen** [comment]
Yeah, I totally agree. I didn't make the companion into a separate class since it meant a whole bunch of work and I wasn't sure if you were interested in the idea :)

I'll have a look at retooling this as soon as I have some spare time.

**Comment by derikb** [comment]
Thinking about it more, is there an advantage in Usability to have it in a separate tab as opposed to just having a second character that you load from the Load menu? I've done that in the past when running a PC and a henchman and it wasn't too onerous. If I add a shortcut for the load/switch character option it would be even easier to toggle between multiple characters.

Then the class itself would stay leaner for saving and the UI would not get anymore complicated.

**Comment by baldurmen** [comment]
Hmm, I agree it does make things more complicated.

I liked the idea of a tab, since companions typically have less features that full-fledged characters, but since we agreed on making this a separate class with the same properties at the main character, I guess it doesn't a ton of sense anymore!

**Pull request closed without merging**
